package ws.domore.lanchonetedelicia;

public enum Categoria {

    SUCOONDATROPICAL,VITAMINAPLANETARIA,HAMBURGUEREXAGERADO,PASTELSUPER,EMPADAOLHOGRANDE,BOLIVIADOQUENTE,QUIBEPOP,ESFIRRADOSABOR,CREPIOCASABOROSA,PAODENUVEM,BRUSCHETTAINTEGRAL

}